using System.Linq.Expressions;
using AutoMapper;
using FluentAssertions;
using HHMCore.Core.Common;
using HHMCore.Core.DTOs.TimeSlot;
using HHMCore.Core.Entities;
using HHMCore.Core.Enums;
using HHMCore.Core.Interfaces;
using HHMCore.Core.Services;
using HHMCore.Tests.Helpers;
using Moq;

namespace HHMCore.Tests.Services;

public class TimeSlotServiceTests
{
    // ── Infrastructure ────────────────────────────────────────────────────────

    private readonly Mock<IUnitOfWork> _uow;
    private readonly Mock<IGenericRepository<TimeSlot>> _timeSlotRepo;
    private readonly Mock<IGenericRepository<CourseAssignment>> _caRepo;
    private readonly IMapper _mapper;
    private readonly TimeSlotService _service;

    // Fixed Guids — never Guid.NewGuid() in static fields
    private static readonly Guid SlotId = new("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa");
    private static readonly Guid OtherId = new("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb");

    // Fixed times used across tests
    private static readonly TimeOnly Start9 = new(9, 0);
    private static readonly TimeOnly End11 = new(11, 0);
    private static readonly TimeOnly End8 = new(8, 0);   // before Start9 — invalid

    public TimeSlotServiceTests()
    {
        _uow = new Mock<IUnitOfWork>();
        _timeSlotRepo = new Mock<IGenericRepository<TimeSlot>>();
        _caRepo = new Mock<IGenericRepository<CourseAssignment>>();
        _mapper = MapperFactory.Create();

        _uow.Setup(u => u.TimeSlots).Returns(_timeSlotRepo.Object);
        _uow.Setup(u => u.CourseAssignments).Returns(_caRepo.Object);

        _service = new TimeSlotService(_uow.Object, _mapper);
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static TimeSlot ExistingSlot() => new()
    {
        Id = SlotId,
        Days = LmsDaysOfWeek.Monday | LmsDaysOfWeek.Wednesday,
        StartTime = Start9,
        EndTime = End11,
        Label = "Mon/Wed 09:00–11:00",
        CreatedAt = DateTime.UtcNow,
        CreatedBy = "admin@test.com",
        IsDeleted = false
    };

    private static CreateTimeSlotDto ValidCreateDto() => new()
    {
        Days = LmsDaysOfWeek.Monday | LmsDaysOfWeek.Wednesday,
        StartTime = Start9,
        EndTime = End11
    };

    // ── CreateAsync ───────────────────────────────────────────────────────────

    [Fact]
    public async Task CreateAsync_ValidRequest_ReturnsSuccess()
    {
        _timeSlotRepo.Setup(r => r.ExistsAsync(It.IsAny<Expression<Func<TimeSlot, bool>>>()))
                     .ReturnsAsync(false);

        var result = await _service.CreateAsync(ValidCreateDto(), "admin@test.com");

        result.Success.Should().BeTrue();
        result.Data.Should().NotBeNull();
    }

    [Fact]
    public async Task CreateAsync_ValidRequest_SavesExactlyOnce()
    {
        _timeSlotRepo.Setup(r => r.ExistsAsync(It.IsAny<Expression<Func<TimeSlot, bool>>>()))
                     .ReturnsAsync(false);

        await _service.CreateAsync(ValidCreateDto(), "admin@test.com");

        _uow.Verify(u => u.SaveChangesAsync(), Times.Once);
    }

    [Fact]
    public async Task CreateAsync_LabelIsAutoGenerated_NotEmpty()
    {
        // A time slot label like "Mon/Wed 09:00–11:00" must be generated by the service
        // It must never be empty — timetable display depends on it
        _timeSlotRepo.Setup(r => r.ExistsAsync(It.IsAny<Expression<Func<TimeSlot, bool>>>()))
                     .ReturnsAsync(false);

        var result = await _service.CreateAsync(ValidCreateDto(), "admin@test.com");

        result.Data!.Label.Should().NotBeNullOrWhiteSpace();
        result.Data.Label.Should().Contain("09:00");
        result.Data.Label.Should().Contain("11:00");
    }

    [Fact]
    public async Task CreateAsync_DuplicateDaysAndTimes_ReturnsFail()
    {
        // Same days + same start + same end already exists in DB
        _timeSlotRepo.Setup(r => r.ExistsAsync(It.IsAny<Expression<Func<TimeSlot, bool>>>()))
                     .ReturnsAsync(true);

        var result = await _service.CreateAsync(ValidCreateDto(), "admin@test.com");

        result.Success.Should().BeFalse();
        result.Message.Should().Contain("already exists");
    }

    [Fact]
    public async Task CreateAsync_EndTimeBeforeStartTime_ReturnsFail()
    {
        // EndTime 08:00 < StartTime 09:00 — corrupt timetable data
        // Must be rejected before the duplicate check even runs
        var dto = ValidCreateDto();
        dto.EndTime = End8;

        var result = await _service.CreateAsync(dto, "admin@test.com");

        result.Success.Should().BeFalse();
        result.Message.Should().Contain("End time must be after start time");
        _uow.Verify(u => u.SaveChangesAsync(), Times.Never);
    }

    [Fact]
    public async Task CreateAsync_EndTimeEqualToStartTime_ReturnsFail()
    {
        // A zero-duration slot makes no sense in a timetable
        var dto = ValidCreateDto();
        dto.EndTime = Start9; // same as StartTime

        var result = await _service.CreateAsync(dto, "admin@test.com");

        result.Success.Should().BeFalse();
        _uow.Verify(u => u.SaveChangesAsync(), Times.Never);
    }

    // ── GetAllAsync ───────────────────────────────────────────────────────────

    [Fact]
    public async Task GetAllAsync_ReturnsAllSlots()
    {
        var slots = new List<TimeSlot> { ExistingSlot() };
        _timeSlotRepo.Setup(r => r.GetAllAsync())
                     .ReturnsAsync(slots);

        var result = await _service.GetAllAsync();

        result.Success.Should().BeTrue();
        result.Data.Should().HaveCount(1);
    }

    [Fact]
    public async Task GetAllAsync_Empty_ReturnsSuccessWithEmptyList()
    {
        _timeSlotRepo.Setup(r => r.GetAllAsync())
                     .ReturnsAsync(new List<TimeSlot>());

        var result = await _service.GetAllAsync();

        result.Success.Should().BeTrue();
        result.Data.Should().BeEmpty();
    }

    // ── GetByIdAsync ──────────────────────────────────────────────────────────

    [Fact]
    public async Task GetByIdAsync_Found_ReturnsSuccess()
    {
        _timeSlotRepo.Setup(r => r.GetByIdAsync(SlotId))
                     .ReturnsAsync(ExistingSlot());

        var result = await _service.GetByIdAsync(SlotId);

        result.Success.Should().BeTrue();
        result.Data.Should().NotBeNull();
    }

    [Fact]
    public async Task GetByIdAsync_NotFound_ReturnsFail()
    {
        _timeSlotRepo.Setup(r => r.GetByIdAsync(SlotId))
                     .ReturnsAsync((TimeSlot?)null);

        var result = await _service.GetByIdAsync(SlotId);

        result.Success.Should().BeFalse();
        result.Message.Should().Contain("not found");
    }

    // ── UpdateAsync ───────────────────────────────────────────────────────────

    [Fact]
    public async Task UpdateAsync_NotFound_ReturnsFail()
    {
        _timeSlotRepo.Setup(r => r.GetByIdAsync(SlotId))
                     .ReturnsAsync((TimeSlot?)null);

        var result = await _service.UpdateAsync(SlotId, new UpdateTimeSlotDto(), "admin@test.com");

        result.Success.Should().BeFalse();
        result.Message.Should().Contain("not found");
    }

    [Fact]
    public async Task UpdateAsync_EmptyDto_RetainsAllExistingValues()
    {
        // Sending null fields means "keep what is already saved"
        // This is the core PUT rule — null = retain existing
        var slot = ExistingSlot();
        _timeSlotRepo.Setup(r => r.GetByIdAsync(SlotId)).ReturnsAsync(slot);
        _timeSlotRepo.Setup(r => r.ExistsAsync(It.IsAny<Expression<Func<TimeSlot, bool>>>()))
                     .ReturnsAsync(false);

        var result = await _service.UpdateAsync(SlotId, new UpdateTimeSlotDto(), "admin@test.com");

        result.Success.Should().BeTrue();
        result.Data!.Label.Should().Contain("09:00");
        result.Data.Label.Should().Contain("11:00");
    }

    [Fact]
    public async Task UpdateAsync_ValidChange_SavesExactlyOnce()
    {
        var slot = ExistingSlot();
        _timeSlotRepo.Setup(r => r.GetByIdAsync(SlotId)).ReturnsAsync(slot);
        _timeSlotRepo.Setup(r => r.ExistsAsync(It.IsAny<Expression<Func<TimeSlot, bool>>>()))
                     .ReturnsAsync(false);

        var dto = new UpdateTimeSlotDto { EndTime = new TimeOnly(12, 0) };
        await _service.UpdateAsync(SlotId, dto, "admin@test.com");

        _uow.Verify(u => u.SaveChangesAsync(), Times.Once);
    }

    [Fact]
    public async Task UpdateAsync_EndTimeBeforeStartTime_ReturnsFail()
    {
        // Even in an update — a slot ending before it starts is corrupt
        var slot = ExistingSlot(); // StartTime = 09:00
        _timeSlotRepo.Setup(r => r.GetByIdAsync(SlotId)).ReturnsAsync(slot);

        // Sending EndTime = 08:00 — before existing StartTime 09:00
        var dto = new UpdateTimeSlotDto { EndTime = End8 };

        var result = await _service.UpdateAsync(SlotId, dto, "admin@test.com");

        result.Success.Should().BeFalse();
        result.Message.Should().Contain("End time must be after start time");
        _uow.Verify(u => u.SaveChangesAsync(), Times.Never);
    }

    [Fact]
    public async Task UpdateAsync_DuplicateDetected_ReturnsFail()
    {
        // Another time slot already has the same days + times
        var slot = ExistingSlot();
        _timeSlotRepo.Setup(r => r.GetByIdAsync(SlotId)).ReturnsAsync(slot);
        _timeSlotRepo.Setup(r => r.ExistsAsync(It.IsAny<Expression<Func<TimeSlot, bool>>>()))
                     .ReturnsAsync(true); // conflict exists

        var dto = new UpdateTimeSlotDto { Days = LmsDaysOfWeek.Tuesday };

        var result = await _service.UpdateAsync(SlotId, dto, "admin@test.com");

        result.Success.Should().BeFalse();
        result.Message.Should().Contain("already exists");
        _uow.Verify(u => u.SaveChangesAsync(), Times.Never);
    }

    // ── DeleteAsync ───────────────────────────────────────────────────────────

    [Fact]
    public async Task DeleteAsync_NotFound_ReturnsFail()
    {
        _timeSlotRepo.Setup(r => r.GetByIdAsync(SlotId))
                     .ReturnsAsync((TimeSlot?)null);

        var result = await _service.DeleteAsync(SlotId, "admin@test.com");

        result.Success.Should().BeFalse();
        result.Message.Should().Contain("not found");
    }

    [Fact]
    public async Task DeleteAsync_HasCourseAssignments_BlocksDelete()
    {
        // A time slot in active use cannot be deleted
        // Timetable integrity must be preserved — reassign classes first
        _timeSlotRepo.Setup(r => r.GetByIdAsync(SlotId)).ReturnsAsync(ExistingSlot());
        _caRepo.Setup(r => r.ExistsAsync(It.IsAny<Expression<Func<CourseAssignment, bool>>>()))
               .ReturnsAsync(true);

        var result = await _service.DeleteAsync(SlotId, "admin@test.com");

        result.Success.Should().BeFalse();
        result.Message.Should().Contain("assigned to one or more classes");
        _uow.Verify(u => u.SaveChangesAsync(), Times.Never);
    }

    [Fact]
    public async Task DeleteAsync_Valid_SoftDeletesAndSaves()
    {
        // Soft delete only — IsDeleted flag set, record stays in DB
        // History preserved — timetable audit trail intact
        _timeSlotRepo.Setup(r => r.GetByIdAsync(SlotId)).ReturnsAsync(ExistingSlot());
        _caRepo.Setup(r => r.ExistsAsync(It.IsAny<Expression<Func<CourseAssignment, bool>>>()))
               .ReturnsAsync(false);

        var result = await _service.DeleteAsync(SlotId, "admin@test.com");

        result.Success.Should().BeTrue();
        _timeSlotRepo.Verify(r => r.Delete(It.IsAny<TimeSlot>()), Times.Once);
        _uow.Verify(u => u.SaveChangesAsync(), Times.Once);
    }
}
